import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';

import FactoryPage from '@/app/factory/page';

describe('factory page', () => {
  it('gives friend trial users a clear ecommerce workbench with real module links and quick actions', async () => {
    const page = await FactoryPage({
      searchParams: Promise.resolve({ variant: 'friend_trial' }),
    });
    const html = renderToStaticMarkup(page);

    expect(html).toContain('/factory/creative?variant=friend_trial');
    expect(html).toContain('/factory/create?variant=friend_trial');
    expect(html).toContain('/factory/video?variant=friend_trial');
    expect(html).toContain('/factory/cast?variant=friend_trial');
    expect(html).toContain('/factory/manage?variant=friend_trial');
    expect(html).toContain('搜索工具 Ctrl K');
    expect(html).toContain('从一个商品，生成一整套可发布内容');
    expect(html).toContain('电商增长闭环');
    expect(html).toContain('功能很多，但客户只看到一条商品增长流水线');
    expect(html).toContain('商品资料进来');
    expect(html).toContain('模特生图和商品证明图');
    expect(html).toContain('客户自己发布');
    expect(html).toContain('表现 CSV');
    expect(html).toContain('发布不代登');
    expect(html).toContain('数据回下一轮');
    expect(html).toContain('每日运营驾驶舱');
    expect(html).toContain('电商人每日运营驾驶舱');
    expect(html).toContain('客户今天只看这些命令');
    expect(html).toContain('客户下一步');
    expect(html).toContain('接入状态');
    expect(html).toContain('客户下一步指挥台');
    expect(html).toContain('先上传商品素材');
    expect(html).toContain('混剪到发布控制台');
    expect(html).toContain('开源混剪、口播标题、客户自发布，先合成一条稳定流水线');
    expect(html).toContain('今天就能稳定混剪');
    expect(html).toContain('多账号标题和口播不做代登');
    expect(html).toContain('发布后用证据驱动下一轮');
    expect(html).toContain('多账号标题矩阵');
    expect(html).toContain('每个平台都有账号人设、标题、前三句口播和证明素材');
    expect(html).toContain('个发布槽');
    expect(html).toContain('证明素材：');
    expect(html).toContain('客户动作：');
    expect(html).toContain('今日渲染队列');
    expect(html).toContain('今天队列能不能稳定出片，客户一眼看懂');
    expect(html).toContain('失败隔离');
    expect(html).toContain('什么时候再升级');
    expect(html).toContain('扩容运行手册');
    expect(html).toContain('大规模渲染不靠一把梭，按三层队列逐步升级');
    expect(html).toContain('客户只看四种状态');
    expect(html).toContain('运营按步骤跑批次');
    expect(html).toContain('扩容路径');
    expect(html).toContain('渲染健康护栏');
    expect(html).toContain('先样片、小批次、抽检、回填，再决定是否上多 worker');
    expect(html).toContain('客户可见放量阶梯');
    expect(html).toContain('首批试跑');
    expect(html).toContain('规模化升级');
    expect(html).toContain('没有真实发布证据时，不购买云渲染或多 worker');
    expect(html).toContain('自发布证据收件箱');
    expect(html).toContain('客户自己发布，我们用证据把下一轮做准');
    expect(html).toContain('回填后系统立刻判断');
    expect(html).toContain('回传上传路径');
    expect(html).toContain('客户回传只走一个云盘目录，缺 API 也能复盘');
    expect(html).toContain('客户上传步骤');
    expect(html).toContain('云盘目录规则');
    expect(html).toContain('上传后产出');
    expect(html).toContain('不向客户索要');
    expect(html).toContain('证明素材和客服承接');
    expect(html).toContain('模特图、证明图和客服话术要接在一起');
    expect(html).toContain('先把证明素材排成任务包');
    expect(html).toContain('客服把内容流量接住');
    expect(html).toContain('客户能看到的边界');
    expect(html).toContain('客户不用理解');
    expect(html).toContain('首版交付清单');
    expect(html).toContain('不等 Key，也能先给客户一套可发布资产');
    expect(html).toContain('客户上线验收');
    expect(html).toContain('客户上线前总验收板');
    expect(html).toContain('满足这些才给客户上线');
    expect(html).toContain('不能对客户承诺');
    expect(html).toContain('首版不用等');
    expect(html).toContain('验收和下一轮');
    expect(html).toContain('交付导航');
    expect(html).toContain('个交付节点');
    expect(html).toContain('客户只按步骤补资料');
    expect(html).toContain('模特生图');
    expect(html).toContain('模特生图先做成任务包');
    expect(html).toContain('个图片任务');
    expect(html).toContain('电商增长闭环');
    expect(html).toContain('电商增长闭环控制台');
    expect(html).toContain('等 Key 时怎么交付');
    expect(html).toContain('为什么功能多但不散');
    expect(html).toContain('下一轮应该改图、改视频、改标题还是改客服');
    expect(html).toContain('开源混剪');
    expect(html).toContain('大规模渲染队列');
    expect(html).toContain('队列治理');
    expect(html).toContain('云盘交付结构');
    expect(html).toContain('首批每个平台至少抽检');
    expect(html).toContain('多账号矩阵先不做自动登录');
    expect(html).toContain('客户自发布操作台');
    expect(html).toContain('客户自发布操作台');
    expect(html).toContain('个发布槽');
    expect(html).toContain('不代登规则');
    expect(html).toContain('超级 IP 和口播标题矩阵');
    expect(html).toContain('超级 IP 标题板');
    expect(html).toContain('超级 IP 标题和口播作战板');
    expect(html).toContain('套标题打法');
    expect(html).toContain('标题质量门');
    expect(html).toContain('标题和口播发布前验收门');
    expect(html).toContain('满足这些才给客户发');
    expect(html).toContain('开源提词器思路');
    expect(html).toContain('回填：');
    expect(html).toContain('个账号人设');
    expect(html).toContain('开源混剪能力地图');
    expect(html).toContain('开源混剪能力地图');
    expect(html).toContain('客户混剪路径');
    expect(html).toContain('客户只看 5 步：素材、片段、模板、渲染、回填');
    expect(html).toContain('给素材 -&gt; 出多平台成片包 -&gt; 自己发布 -&gt; 回填复盘');
    expect(html).toContain('Auto-Editor');
    expect(html).toContain('MediaInfo');
    expect(html).toContain('GitHub 开源混剪蓝图');
    expect(html).toContain('GitHub 开源混剪蓝图');
    expect(html).toContain('一个商品项目统一多种开源能力');
    expect(html).toContain('程序化模板 + 稳定队列批量出片');
    expect(html).toContain('进入交付的规则');
    expect(html).toContain('开源混剪能力雷达');
    expect(html).toContain('GitHub 开源混剪能力雷达');
    expect(html).toContain('开源能力接入队列');
    expect(html).toContain('GitHub 开源能力接入队列');
    expect(html).toContain('类开源范式');
    expect(html).toContain('大规模渲染和云端 worker');
    expect(html).toContain('客户可见的上线标准');
    expect(html).toContain('仍然不等外部接入');
    expect(html).toContain('moneyprinterturbo');
    expect(html).toContain('short-video-maker');
    expect(html).toContain('video-wizard');
    expect(html).toContain('opencut-ai');
    expect(html).toContain('clipsai');
    expect(html).toContain('supoclip');
    expect(html).toContain('混剪队列控制台');
    expect(html).toContain('开源混剪队列控制台');
    expect(html).toContain('交付最后一公里');
    expect(html).toContain('开源混剪最后一公里判断板');
    expect(html).toContain('客户最后一步');
    expect(html).toContain('开源不解决');
    expect(html).toContain('稳定渲染和单条重试');
    expect(html).toContain('客户可见证据');
    expect(html).toContain('开源混剪栈选择器');
    expect(html).toContain('开源混剪栈选择器');
    expect(html).toContain('long-material-slicing');
    expect(html).toContain('stable-render');
    expect(html).toContain('安装和冒烟验收');
    expect(html).toContain('开源混剪安装和冒烟验收矩阵');
    expect(html).toContain('进入客户交付前必须满足');
    expect(html).toContain('开源能力适配器');
    expect(html).toContain('执行配方');
    expect(html).toContain('每个开源能力都落到输入、步骤、输出和验收');
    expect(html).toContain('开源混剪编排板');
    expect(html).toContain('客户看到的是 5 步稳定流水线');
    expect(html).toContain('平台自动登录不是首版阻塞项');
    expect(html).toContain('稳定渲染看板');
    expect(html).toContain('稳定渲染看板');
    expect(html).toContain('稳定渲染运行手册');
    expect(html).toContain('稳定渲染运行手册');
    expect(html).toContain('按批渲染');
    expect(html).toContain('单条重试');
    expect(html).toContain('客户看到的状态');
    expect(html).toContain('状态恢复规则');
    expect(html).toContain('单条重试');
    expect(html).toContain('客户看到的是一条商品增长流水线');
    expect(html).toContain('没有外部接入时的替代路径');
    expect(html).toContain('chat Cut 式精简混剪控制台');
    expect(html).toContain('chat Cut 式精简混剪控制台');
    expect(html).toContain('改前三秒');
    expect(html).toContain('换证明素材');
    expect(html).toContain('批量换标题');
    expect(html).toContain('只重跑失败条');
    expect(html).toContain('步混剪流');
    expect(html).toContain('证明优先');
    expect(html).toContain('客户只看这些');
    expect(html).toContain('外部接入判断');
    expect(html).toContain('什么时候再升级');
    expect(html).toContain('外部平台服务升级判断板');
    expect(html).toContain('满足这些再配');
    expect(html).toContain('Key 接入步骤');
    expect(html).toContain('Key 到位后的接入运行手册');
    expect(html).toContain('不在页面、日志或导出包展示 Key 值');
    expect(html).toContain('首版可交付');
    expect(html).toContain('客户自发布');
    expect(html).toContain('客户回填字段');
    expect(html).toContain('人设发布操作台');
    expect(html).toContain('多账号人设发布矩阵');
    expect(html).toContain('前三句口播');
    expect(html).toContain('客户自己登录');
    expect(html).toContain('回填后系统看什么');
    expect(html).toContain('表现证据验收');
    expect(html).toContain('客户表现证据验收板');
    expect(html).toContain('客户证据上传指南');
    expect(html).toContain('客户证据上传指南');
    expect(html).toContain('回传四类证据');
    expect(html).toContain('不向客户索要');
    expect(html).toContain('发布后行动板');
    expect(html).toContain('发布后复盘行动板');
    expect(html).toContain('可进入下一轮');
    expect(html).toContain('仍然不自动化');
    expect(html).toContain('建议并发');
    expect(html).toContain('客服素材');
    expect(html).toContain('售前承接');
    expect(html).toContain('差评挽回');
    expect(html).toContain('对话运营板');
    expect(html).toContain('售前、推荐、售后和复购');
    expect(html).toContain('chat Cut 式电商对话工单台');
    expect(html).toContain('chat Cut 式电商对话工单台');
    expect(html).toContain('客户上传后怎么走');
    expect(html).toContain('不能自动化');
    expect(html).toContain('个回复包');
    expect(html).toContain('不自动登录客户平台账号');
    expect(html).toContain('Wenai 商品增长工作台');
    expect(html).not.toContain('provider 待配置');
    expect(html).not.toContain('小W 在线');
    expect(html).toContain('回填收件箱');
    expect(html).toContain('可复盘');
    expect(html).toContain('已收');
    expect(html).not.toContain('provider');
    expect(html).not.toContain('OAuth');
    expect(html).not.toContain('analytics sync');
    expect(html).not.toContain('analytics API');
    expect(html).not.toContain('CRM');
    expect(html).not.toContain('SKU');
    expect(html).not.toContain('Customer Launch Readiness');
    expect(html).not.toContain('Evidence Readiness');
    expect(html).not.toContain('Action Queue');
    expect(html).not.toContain('External Gates');
    expect(html).not.toContain('SYSTEM LOGS');
    expect(html).not.toContain('授权辅助');
    expect(html).not.toContain('需要代操作');
    expect(html).not.toContain('辅助执行');
    expect(html).not.toContain('fixed bottom-5 right-5');
    expect(html).not.toContain('86%');
  });
});
